config/routes.rb
Tennis2app::Application.routes.draw do

  resources :courts
  root 'courts#index'

end

app/models/court.rb
class Court
  include Mongoid::Document
  field :court_num, type: Integer
  field :booked, type: :Boolean
  has_many :players

  validates :court_num, presence: true, numericality: true, uniqueness: true

end

app/models/player.rb
class Player
  include Mongoid::Document
  field :name, type: String
  belongs_to :court
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController

	def index
		@courts = Court.all
	end

	def new
		@court = Court.new
	end

	def create
		@court = Court.new(court_params)
		if @court.save
			redirect_to action: 'index'
			flash[:notice] = 'You successfully added a new court!'
		else
			render action: 'new'
		end

	end

	def edit
		@court = Court.find(params[:id])
		render action: 'new'
	end

	def update
		@court = Court.find(params[:id])
		if @court.update(court_params)
			redirect_to action: 'index'
			flash[:notice] = 'You successfully updated the info for Court ' + @court.court_num.to_s + '!'
		else
			render action: 'edit'
		end
	end

	def destroy
		@court = Court.find(params[:id])
		@court.destroy
		redirect_to action: 'index'
	end

	def show
		@court = Court.find(params[:id])
	end


private

	def court_params
		params.require(:court).permit(:court_num, :booked)
	end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/courts/_form.html.erb
<%= form_for @court do |f| %>
<p>
	<%= f.label :'Court number: ' %>
	<%= f.text_field :court_num %>
</p>
<p>
	<%= f.label :'Status: ' %>
	<%= f.select :booked, [['booked', true], ['open', false]] %>
</p>
<br />
<%= f.submit %>
<% end %>

app/views/courts/edit.html.erb
<h1>Edit Court</h1>

<%= render partial: 'form' %>

<%= link_to 'Back', courts_path %>

app/views/courts/index.html.erb
<h1>Welcome to the Tennis Club!</h1>
<br />
<p id="notice"><%= notice %></p>
<br />
<table>
	<thead>
		<tr>
			<th>Court Number</th>
			<th>Status</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @courts.each do |court| %>
			<tr>
				<td class="court_column"><%= link_to "#{court.court_num}", court_path(court) %></td>
				<td><%= court.booked ? "booked" : "open" %></td>
				<td class="mini_column"><%= link_to 'Edit', edit_court_path(court) %></td>
				<td class="mini_column"><%= link_to 'Remove', court, method: :delete, data: {confirm: 'Are you sure?'} %></td>
			</tr>
		<% end %>	
	</tbody>
</table>
<br />
<%= link_to 'New Court', new_court_path %>

app/views/courts/new.html.erb
<h1>Add a New Court</h1>
<br />
<%= render partial: 'form' %>
<br />

<%= link_to 'Back', courts_path %>

app/views/courts/show.html.erb
<h1>Court Info</h1>

<p>Court number: <%= @court.court_num %></p>
<p>Court status: <%= @court.booked ? "booked" : "open" %></p>

<%= link_to 'Back', courts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tennis2app</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>